# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"console": "constants.ipynb",
         "ESTADOS": "constants.ipynb",
         "SIGLAS": "constants.ipynb",
         "REGEX_ESTADOS": "constants.ipynb",
         "TIMEOUT": "queries.ipynb",
         "RELATORIO": "queries.ipynb",
         "ESTACOES": "queries.ipynb",
         "ESTACAO": "queries.ipynb",
         "PLANO_BASICO": "queries.ipynb",
         "HISTORICO": "queries.ipynb",
         "REJECT_ESTACOES": "queries.ipynb",
         "COL_ESTACOES": "queries.ipynb",
         "NEW_ESTACOES": "queries.ipynb",
         "COL_PB": "queries.ipynb",
         "NEW_PB": "queries.ipynb",
         "TELECOM": "queries.ipynb",
         "RADIODIFUSAO": "queries.ipynb",
         "APP_ANALISE": "queries.ipynb",
         "ENTIDADES": "queries.ipynb",
         "RADCOM": "queries.ipynb",
         "STEL": "queries.ipynb",
         "formatar_db": "filter.ipynb",
         "optimize_floats": "queries.ipynb",
         "optimize_ints": "queries.ipynb",
         "optimize_objects": "queries.ipynb",
         "df_optimize": "queries.ipynb",
         "connect_db": "queries.ipynb",
         "row2dict": "queries.ipynb",
         "dict2cols": "queries.ipynb",
         "parse_plano_basico": "queries.ipynb",
         "scrape_dataframe": "queries.ipynb",
         "read_stel": "queries.ipynb",
         "read_radcom": "queries.ipynb",
         "read_estações": "queries.ipynb",
         "read_plano_basico": "queries.ipynb",
         "read_historico": "queries.ipynb",
         "read_mosaico": "queries.ipynb",
         "read_base": "queries.ipynb",
         "clean_merge": "queries.ipynb",
         "update_radcom": "queries.ipynb",
         "update_stel": "queries.ipynb",
         "update_mosaico": "queries.ipynb",
         "update_base": "queries.ipynb"}

modules = ["constants.py",
           "filter.py",
           "query.py"]

doc_url = "https://ronaldokun.github.io/anateldb/"

git_url = "https://github.com/ronaldokun/anateldb/tree/master/"

def custom_doc_links(name): return None
