# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"console": "constants.ipynb",
         "ESTADOS": "constants.ipynb",
         "SIGLAS": "constants.ipynb",
         "REGEX_ESTADOS": "constants.ipynb",
         "TIMEOUT": "constants.ipynb",
         "RELATORIO": "constants.ipynb",
         "ESTACOES": "constants.ipynb",
         "ESTACAO": "constants.ipynb",
         "PLANO_BASICO": "constants.ipynb",
         "HISTORICO": "constants.ipynb",
         "REJECT_ESTACOES": "constants.ipynb",
         "COL_ESTACOES": "constants.ipynb",
         "NEW_ESTACOES": "constants.ipynb",
         "COL_PB": "constants.ipynb",
         "NEW_PB": "constants.ipynb",
         "TELECOM": "constants.ipynb",
         "RADIODIFUSAO": "constants.ipynb",
         "APP_ANALISE": "constants.ipynb",
         "ENTIDADES": "constants.ipynb",
         "RADCOM": "constants.ipynb",
         "STEL": "constants.ipynb",
         "bump_version": "filter.ipynb",
         "append_df_to_excel": "filter.ipynb",
         "get_modtimes": "filter.ipynb",
         "formatar_db": "filter.ipynb",
         "BW": "queries.ipynb",
         "BW_pattern": "queries.ipynb",
         "BW_MAP": "queries.ipynb",
         "optimize_floats": "queries.ipynb",
         "optimize_ints": "queries.ipynb",
         "optimize_objects": "queries.ipynb",
         "df_optimize": "queries.ipynb",
         "connect_db": "queries.ipynb",
         "row2dict": "queries.ipynb",
         "dict2cols": "queries.ipynb",
         "parse_plano_basico": "queries.ipynb",
         "scrape_dataframe": "queries.ipynb",
         "input_coordenates": "queries.ipynb",
         "clean_merge": "queries.ipynb",
         "parse_bw": "queries.ipynb",
         "read_estações": "queries.ipynb",
         "read_plano_basico": "queries.ipynb",
         "update_radcom": "queries.ipynb",
         "update_stel": "queries.ipynb",
         "update_mosaico": "queries.ipynb",
         "read_aero": "queries.ipynb",
         "merge_aero": "queries.ipynb",
         "update_base": "queries.ipynb",
         "read_stel": "queries.ipynb",
         "read_radcom": "queries.ipynb",
         "read_mosaico": "queries.ipynb",
         "read_icao": "queries.ipynb",
         "read_pmec": "queries.ipynb",
         "read_geo": "queries.ipynb",
         "read_base": "queries.ipynb"}

modules = ["constants.py",
           "filter.py",
           "query.py"]

doc_url = "https://ronaldokun.github.io/anateldb/"

git_url = "https://github.com/ronaldokun/anateldb/tree/master/"

def custom_doc_links(name): return None
