# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"filter_database": "filter.ipynb",
         "read_stel": "parser.ipynb",
         "read_radcom": "parser.ipynb",
         "row2dict": "parser.ipynb",
         "dict2cols": "parser.ipynb",
         "parse_plano_basico": "parser.ipynb",
         "read_estações": "parser.ipynb",
         "read_plano_basico": "parser.ipynb",
         "read_historico": "parser.ipynb",
         "read_mosaico": "parser.ipynb",
         "ESTACOES": "queries.ipynb",
         "PLANO_BASICO": "queries.ipynb",
         "HISTORICO": "queries.ipynb",
         "REJECT_ESTACOES": "queries.ipynb",
         "COL_ESTACOES": "queries.ipynb",
         "NEW_ESTACOES": "queries.ipynb",
         "COL_PB": "queries.ipynb",
         "NEW_PB": "queries.ipynb",
         "TELECOM": "queries.ipynb",
         "RADIODIFUSAO": "queries.ipynb",
         "RADCOM": "queries.ipynb",
         "STEL": "queries.ipynb",
         "connect_db": "queries.ipynb",
         "update_radcom": "queries.ipynb",
         "update_stel": "queries.ipynb",
         "update_mosaico": "queries.ipynb",
         "URL": "redmine.ipynb",
         "URLHM": "redmine.ipynb",
         "URLHM2": "redmine.ipynb",
         "ACAO_DESCRIPTION": "redmine.ipynb",
         "ACAO_TRACKER": "redmine.ipynb",
         "FIELDS": "redmine.ipynb",
         "CUSTOM_IDS": "redmine.ipynb",
         "SITUACAO": "redmine.ipynb",
         "CLASSE": "redmine.ipynb",
         "TIPO": "redmine.ipynb",
         "STATUS": "redmine.ipynb",
         "SERVICOS": "redmine.ipynb",
         "DICT_FIELD": "redmine.ipynb",
         "ID2FIELD": "redmine.ipynb",
         "FIELD2ID": "redmine.ipynb",
         "validate_datadict": "redmine.ipynb",
         "value_text_string": "redmine.ipynb",
         "auth_user": "redmine.ipynb",
         "issue2users": "redmine.ipynb",
         "insp2acao": "redmine.ipynb",
         "detalhar_inspecao": "redmine.ipynb",
         "rascunho2aguardando": "redmine.ipynb",
         "aguardando2andamento": "redmine.ipynb",
         "andamento2relatando": "redmine.ipynb",
         "relatando2relatado": "redmine.ipynb"}

modules = ["filter.py",
           "parser.py",
           "query.py",
           "redmine.py",
           "tests.py"]

doc_url = "https://ronaldokun.github.io/anateldb/"

git_url = "https://github.com/ronaldokun/anateldb/tree/master/"

def custom_doc_links(name): return None
