# AUTOGENERATED! DO NOT EDIT! File to edit: constants.ipynb (unless otherwise specified).

__all__ = ['URL', 'URLHM', 'URLHM2', 'ACAO_DESCRIPTION', 'ACAO_TRACKER', 'FIELDS', 'CUSTOM_IDS', 'SITUACAO',
           'DICT_FIELDS', 'CLASSE', 'TIPO', 'STATUS', 'SERVICOS', 'ID2FIELD', 'FIELD2ID', 'ESTADOS', 'SIGLAS',
           'REGEX_ESTADOS']

# Cell
URL = 'https://sistemas.anatel.gov.br/fiscaliza/'
URLHM = 'https://sistemashm.anatel.gov.br/fiscaliza'
URLHM2 = 'https://sistemasnethm/fiscaliza'
ACAO_DESCRIPTION = 54
ACAO_TRACKER = 2

# Cell
FIELDS = ['id', 'subject', 'status', 'priority', 'start_date', 'due_date']
CUSTOM_IDS = [89, 2, 22, 25, 26, 595, 156, 157, 158, 159, 31, 57, 69, 70, 91, 92, 93, 94, 170, 171]

SITUACAO ={'Rascunho': 1,
            'Aguardando Execução': 11,
            'Em andamento': 13,
            'Relatando': 14,
            'Relatada': 15,
            'Cancelada': 19}

DICT_FIELDS = ('Classe da Inspeção', 'Tipo de inspeção', 'Descrição da Inspeção', 'Fiscal responsável ',
              'Fiscais ', 'Html', ' Gerar Relatório ', 'Frequência inicial', 'Unidade da frequência inicial',
              'Frequência final', 'Unidade da frequência final', 'Data de início', 'Data limite',
              'UF/Município', 'Serviços da Inspeção', 'Qnt. de emissões na faixa', 'Emissões não autorizadas/desc',
              'Horas de Preparação', 'Horas de Deslocamento', 'Horas de Execução', 'Horas de conclusão', 'Latitude (coordenadas)',
              'Longitude (coordenadas)', 'Uso de PF', 'Ação de risco à vida criada?', 'Impossibilidade acesso online?', 'notes')

CLASSE = ('Tributária',
          'Técnica',
          'Serviço')

TIPO = ('Outorga - Aspectos não Técnicos',
        'Medição de CEMRF (RNI)',
        'Outorga - Aspectos Técnicos',
        'TV Digital',
        'Uso do Espectro - Monitoração',
        'Uso do Espectro - Não Outorgado',
        'Certificação')

STATUS = {'Aguardando Execução': ('Classe da Inspeção', 'Tipo de inspeção', 'Descrição da Inspeção', 'Fiscal responsável ', 'Fiscais '),
          'Em andamento': ('Html', ' Gerar Relatório '),
          'Relatando': ('Frequência inicial', 'Frequência final', 'Unidade da frequência inicial', 'Unidade da frequência final'),
          'Relatada' : ('UF/Município', 'Serviços da Inspeção', 'Qnt. de emissões na faixa', 'Emissões não autorizadas/desc',
                        'Horas de Preparação', 'Horas de Deslocamento', 'Horas de Execução', 'Horas de conclusão', 'Latitude (coordenadas)',
                        'Longitude (coordenadas)', 'Uso de PF', 'Ação de risco à vida criada?', 'Impossibilidade acesso online?')}

SERVICOS = {'230' : '230 - COLETIVO - RADIODIFUSÃO SONORA EM FREQÜÊNCIA MODULADA',
            '231' : '231 - COLETIVO - RADIODIFUSÃO COMUNITÁRIA',
            '507' : '507 - RESTRITO - MÓVEL AERONÁUTICO',
            '019' : '019 - RESTRITO - LIMITADO PRIVADO',
            '800' : '800 - COLETIVO - RETRANSMISSAO DE T.V.',
            '205' : '205 - COLETIVO - RADIODIFUSÃO SONORA EM ONDA MÉDIA',
            '248' : '248 - COLETIVO - RADIODIFUSÃO DE SONS E IMAGENS',
            '167' : '167 - COLETIVO - ESPECIAL DE TELEVISAO POR ASSINATURA',
            '801' : '801 - COLETIVO - RETRANSMISSÃO DE RADIODIFUSÃO DE SONS E IMAGENS - DIGITAL',
            '247' : '247 - COLETIVO - GERADORA DE RADIODIFUSÃO DE SONS E IMAGENS - DIGITAL',
            '035' : '035 - RESTRITO - ESPC. P/FINS CIENTIF.EXPERIMENTAIS',
            '078' : '078 - RESTRITO - SERVIÇO DE RADIOTÁXI PRIVADO',
            '079' : '079 - COLETIVO - SERVIÇO DE RADIOTÁXI ESPECIALIZADO',
            '033' : '033 - COLETIVO - RADIOENLACES ASSOCIADOS AO SERVIÇO DE RÁDIOTAXI',
            '108' : '108 - RESTRITO - SERVIÇO LIMITADO PRIVADO SUBMODALIDADE RADIODETERMINAÇÃO',
            '132' : '108 - RESTRITO - ESPECIAL DE RADIOAUTOCINE',
            '017' : '017 - RESTRITO - LIMITADO ESPECIALIZADO',
            '011' : '011 - RESTRITO - LIMITADO PRIVADO - PRESTAÇÃO A TERCEIROS',
            '124' : '124 - RESTRITO - ESPECIAL DE SUPERVISÃO E CONTROLE/USO PRÓPRIO',
            '125' : '125 - RESTRITO - ESPECIAL DE SUPERVISÃO E CONTROLE/TERCEIROS',
            '604' : '604 - RESTRITO - MÓVEL MARÍTIMO',
            '064' : '064 - COLETIVO - MÓVEL MARÍTIMO ESPECIALIZADO',
            '046' : '046 - COLETIVO - RADIOENLACES ASSOCIADOS AO SCM',
            '053' : '053 - COLETIVO - RADIOENLACES ASSOCIADOS AO SMP',
            '099' : '099 - RESTRITO - SERVIÇO DE RADIAÇÃO RESTRITA',
            '012' : '012 - RESTRITO - RADIOENLACES ASSOCIADOS AO SERVIÇO MÓVEL PRIVADO'}

ID2FIELD = {
89: 'Classe da Inspeção',
2: 'Tipo de inspeção',
22: 'Descrição da Inspeção',
25: 'Fiscal responsável ',
26: 'Fiscais ',
585: 'Html',
595: 'Relatório de Monitoramento',
588: ' Gerar Relatório ',
156: 'Frequência inicial',
157: 'Unidade da frequência inicial',
158: 'Frequência final',
159: 'Unidade da frequência final',
31: 'UF/Município',
57: 'Serviços da Inspeção',
69: 'Qnt. de emissões na faixa',
70: 'Emissões não autorizadas/desc',
91: 'Horas de Preparação',
92: 'Horas de Deslocamento',
93: 'Horas de Execução',
94: 'Horas de conclusão',
170: 'Latitude (coordenadas)',
171: 'Longitude (coordenadas)',
151: 'Uso de PF',
154: 'Ação de risco à vida criada?',
450: 'Impossibilidade acesso online?'}

FIELD2ID = {'Classe da Inspeção': 89,
 'Tipo de inspeção': 2,
 'Descrição da Inspeção': 22,
 'Fiscal responsável ': 25,
 'Fiscais ': 26,
 'Relatório de Monitoramento': 595,
 ' Gerar Relatório ': 588,
 'Html': 585, #Campo Oculto
 'Frequência inicial': 156,
 'Unidade da frequência inicial': 157,
 'Frequência final': 158,
 'Unidade da frequência final': 159,
 'UF/Município': 31,
 'Serviços da Inspeção': 57,
 'Qnt. de emissões na faixa': 69,
 'Emissões não autorizadas/desc': 70,
 'Horas de Preparação': 91,
 'Horas de Deslocamento': 92,
 'Horas de Execução': 93,
 'Horas de conclusão': 94,
 'Latitude (coordenadas)': 170,
 'Longitude (coordenadas)': 171,
 'Uso de PF': 151,
 'Ação de risco à vida criada?': 154,
 'Impossibilidade acesso online?': 450}

# Cell
ESTADOS = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'ES', 'GO', 'MA', 'MT', 'MS',
           'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR',
           'SC', 'SP', 'SE', 'TO', 'DF']

SIGLAS = {"Acre" : "AC",
          "Alagoas" : "AL",
          "Amapá": "AP",
          "Amazonas":"AM",
          "Bahia":"BA",
          "Ceará":"CE",
          "Espírito Santo":"ES",
          "Goiás":"GO",
          "Maranhão":"MA",
          "Mato Grosso":"MT",
          "Mato Grosso do Sul":"MS",
          "Minas Gerais": "MG",
          "Pará": "PA",
          "Paraíba":"PB",
          "Paraná":"PR",
          "Pernambuco":"PE",
          "Piauí":"PI",
          "Rio de Janeiro":"RJ",
          "Rio Grande do Norte":"RN",
          "Rio Grande do Sul":"RS",
          "Rondônia":"RO",
          "Roraima":"RR",
          "Santa Catarina":"SC",
          "São Paulo":"SP",
          "Sergipe":"SE",
          "Tocantins":"TO",
          "Distrito Federal":"DF"}

REGEX_ESTADOS = f'({"|".join(ESTADOS)})'