# AUTOGENERATED! DO NOT EDIT! File to edit: filter.ipynb (unless otherwise specified).

__all__ = ['filter_database']

# Cell
from pathlib import Path
from datetime import datetime
from .parser import *

# Cell
def filter_database(path):
    path = Path(path)
    time = datetime.today().strftime("%Y-%m-%d_%H-%M")
    mosaico = read_mosaico()
    stel = read_stel().sort_values('Frequência')
    radcom = read_radcom()
    radcom['Serviço'] = 'RADCOM'
    radcom['Classe'] = 'Até 25W'
    radcom['Situação'] = radcom.Serviço + '-' + radcom.Situação
    radcom.rename({'Numero da Estação': 'Número da Estação'}, axis=1, inplace=True)
    radcom = radcom.loc[:, RADIODIFUSAO]
    mosaico = mosaico.loc[:, RADIODIFUSAO]
    radiodifusao = mosaico.append(radcom).sort_values('Frequência')
    radiodi
    slma = (stel.Frequência >= 108) & (stel.Frequência <= 137)
    telecom = stel[~slma].reset_index()
    slma = stel[slma].reset_index()
    mosaico.to_csv(f'{path}/radiodifusao_{time}.csv', index=False)
    slma.to_csv(f'{path}/108-137_{time}.csv', index=False)
    telecom.to_csv(f'{path}/telecom_{time}.csv', index=False)
    mosaico.to_feather(f'{path}/radiodifusao_{time}.fth')
    slma.to_feather(f'{path}/108-137_{time}.fth')
    telecom.to_feather(f'{path}/telecom_{time}.fth')
    with pd.ExcelWriter(f'{path}/Base_de_Dados_{time}.xlsx') as workbook:
        mosaico.to_excel(workbook, sheet_name='radiodifusão', index=False)
        slma.to_excel(workbook, sheet_name='108-137', index=False)
        telecom.to_excel(workbook, sheet_name='Telecom', index=False)