# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MOSAICO": "queries.ipynb",
         "RADCOM": "queries.ipynb",
         "download_mosaico": "queries.ipynb"}

modules = ["query.py"]

doc_url = "https://ronaldokun.github.io/anatelspyder/"

git_url = "https://github.com/ronaldokun/anatelspyder/tree/master/"

def custom_doc_links(name): return None
